function blog_user_can_edit_entry($blogentry)
function blog_user_can_view_user_entry($targetuserid, $blogentry=null)
function blog_remove_associations_for_user($userid)
function blog_remove_associations_for_course($courseid)
function blog_remove_associations_for_module($modcontextid)
function blog_sync_external_entries($externalblog)
function blog_delete_external_entries($externalblog)
function blog_is_enabled_for_user()
function blog_get_all_options(moodle_page $page, stdClass $userid = null)
function blog_get_options_for_user(stdClass $user=null)
function blog_get_options_for_course(stdClass $course, stdClass $user=null)
function blog_get_options_for_module($module, $user=null)
function blog_get_headers($courseid=null, $groupid=null, $userid=null, $tagid=null, $tag=null, $modid=null, $entryid=null, $search = null)
function blog_get_associated_count($courseid, $cmid=null)
function blog_comment_permissions($commentparam)
function blog_comment_validate($commentparam)
function blog_page_type_list($pagetype, $parentcontext, $currentcontext)
function core_blog_myprofile_navigation(core_user\output\myprofile\tree $tree, $user, $iscurrentuser, $course)
function blog_get_tagged_posts($tag, $exclusivemode = false, $fromctx = 0, $ctx = 0, $rec = true, $page = 0)
function blog_validate_access($courseid, $modid, $groupid, $entryid, $userid)
